define({
	code: "en",
	strings: {
		ACHIEVEMENTS: "Achievements",
		ACHIEVEMENT_EARNED: "Achievement Earned! %s",
		AMOUNT_EARNED: "%s / %s earned",
		ANALOG_DEAD_ZONE_LEFT: "Analog dead zone (left)",
		ANALOG_DEAD_ZONE_RIGHT: "Analog dead zone (right)",
		ARMOR_SHOP: "Armor Shop",
		ATTACK_UP: "Attack Up",
		ATTACK_LEFT: "Attack Left",
		ATTACK_DOWN: "Attack Down",
		ATTACK_RIGHT: "Attack Right",
		BACK: "Back",
		BLUEPRINT_X: "Blueprint: %s",
		CHALLENGE_CTA: "To issue a challenge, copy this URL and give it to a friend:",
		CHALLENGER: "Challenger",
		CONTINUE: "Continue",
		CELEBRATE_KILL: "Killed %s %s times!",
		CHARACTER_RAGA: "Raga",
		CHARACTER_RAGADARK: "Raga",
		CHARACTER_ENGINEER: "The Engineer",
		CHARACTER_WIZARD: "Wizard",
		CHARACTER_LUNA: "Luna",
		CHARACTER_MOTO: "Moto",
		COMMISSIONED_BY: "Commissioned by %s",
		COMPLETE: "Complete!",
		COPYRIGHT: "v%s © Lost Decade Games",
		DAMAGE_TAKEN: "Damage Taken",
		DANGER: "Danger!",
		DARKNESS: "Darkness",
		DASH: "Dash",
		DECREASES_X: "Decreases %s",
		DISABLED: "Disabled",
		DUNGEON_COMPLETE: "%s Complete",
		ENABLED: "Enabled",
		EQUIPMENT: "Equipment",
		FIRST_KILL: "First kill! %s",
		FULLSCREEN: "Fullscreen",
		GAME_OVER: "GAME OVER",
		GAMEPAD: "Gamepad",
		GAMEPAD_STATUS: "Gamepad: %s",
		GOLD_MONSTER_STATUE_EARNED: "EPIC! Mastered killing %s.",
		GRAND_HALL: "Grand Hall",
		HALL_OF_ARMOR: "Hall of Defense",
		HALL_OF_PATRONS: "Hall of Patrons",
		HALL_OF_MONSTERS: "Monster Hall",
		HALL_OF_ITEMS: "Hall of Artifacts",
		HALL_OF_WEAPONS: "Hall of War",
		HALL_OF_CEMETERY: "Hall of Graves",
		HALL_OF_SEWER: "Hall of Muck",
		HALL_OF_CRYPT: "Hall of the Dead",
		HUD_ITEMS_OFF: "Show HUD inventory",
		INCOMPLETE: "Incomplete",
		INCREASES_X: "Increases %s",
		INPUT_START: "Please press A on gamepad",
		INTERACT: "Interact",
		INVENTORY: "Inventory",
		HIDE_UI: "Hide UI",
		ITEM_SHOP: "Item Shop",
		KEY_BINDINGS: "Key Bindings",
		LIGHT_EFFECTS: "Lighting Effects",
		DELETE_DATA: "Delete save data",
		DELETE_DATA2: "REALLY delete save data!",
		MAP: "Map",
		MARKETPLACE: "Marketplace",
		MENU_LEFT: "Menu left",
		MENU_RIGHT: "Menu right",
		MOVE_UP: "Move Up",
		MOVE_LEFT: "Move Left",
		MOVE_DOWN: "Move Down",
		MOVE_RIGHT: "Move Right",
		MUSEUM: "Museum",
		MUSEUM_LAB: "Museum Laboratory",
		MUSEUM_LIBRARY: "Museum Library",
		MUSEUM_LOBBY: "Museum Lobby",
		MUSEUM_MAIN_HALL: "Museum Main Hall",
		MUSEUM_MONSTER_HALL: "Museum Monster Hall",
		MUSEUM_WEST_HALL: "Museum West Hall",
		MUSEUM_QUARTERS: "Museum Living Quarters",
		MUSEUM_STOREROOM: "Museum Storeroom",
		MUSIC_ON: "Disable music",
		MUSIC_OFF: "Enable music",
		MUSIC_VOLUME: "Music volume",
		NEXT: "Next",
		NONE: "None",
		OPTIONS: "Options",
		PARTICLE_EFFECTS: "Particle Effects",
		PLAY: "Play",
		PLAYER_SELECT: "Choose a Character",
		PROGRESS_START: "Defeat Death",
		PRESS_BUTTON: "Press any face button",
		TAB_LEFT: "or press [",
		TAB_RIGHT: "or press ]",
		RETURN_TO_TITLE: "Return to title",
		RESTART: "Play again",
		CHARACTER_SELECT: "Character selection",
		SCREEN_SHAKE: "Shake the screen",
		TITLE: "Return to title",
		QUIT: "Quit",
		QUIT2: "Really quit",
		RESET_TO_DEFAULTS: "Reset to defaults",
		SETTINGS: "Settings",
		SOUND_VOLUME: "Sound volume",
		STATUES_EARNED: "New monsters killed",
		SWAP_ANALOGS: "Swap analogs",
		HOSTAGES_RESCUED: "Townsfolk rescued",
		TAVERN: "Tavern",
		TIME: "Time",
		TIME_N: "Time: %s",
		TREASURE: "Treasure",
		UPDATE_AVAILABLE: "Update available - click here",
		USE_SOUL_ORB: "Use Soul Orb",
		USE_TOTEM: "Use Totem",
		WEAPON_SHOP: "Weapon Shop",
		YOU: "You",

		CREDITS: "Credits",
		MAKERS: "Design & Programming",
		ART: "Art",
		AUDIO: "Music & Sound Effects",
		BIZDEV: "Marketing & Business Development",
		BRONZE_SPONSORS: "Bronze Sponsors",
		SILVER_SPONSORS: "Silver Sponsors",
		GOLD_SPONSORS: "Gold Sponsors",
		SPECIAL_THANKS: "Special Thanks",
		THE_END: "Thank you for playing A Wizard's Lizard!",

		WINS_LOSSES: "Wins: %s, Deaths: %s",

		DIALOG_SEWER_LOCKED: "This shortcut leads to the Sewer, but the way is blocked by mysterious green crystals.",
		DIALOG_SEWER_UNLOCKED: "Looks like you cleared out the crystals, well done! The Sewer shortcut is now open.",
		DIALOG_CRYPT_LOCKED: "This shortcut leads to the Crypt, but the way is blocked by mysterious red crystals.",
		DIALOG_CRYPT_UNLOCKED: "Looks like you cleared out the crystals, well done! The Crypt shortcut is now open.",
		DIALOG_ARENA_INFO: "Only the most proven warriors may test their skill in the Arena. When you reach %s kills, you'll be allowed to enter. You've killed %s monsters so far.",

		DIALOG_LUNA_RESCUE: "Ah, thanks for rescuing me! I thought I would burn in all this lava... I'll help you fight the forces of Death.",
		DIALOG_MOTO_RESCUE: "Grr, I was born to fight. Those demons captured me and now I want REVENGE! Grr, I'll help you fight the forces of Death.",
		DIALOG_ENGINEER_RESCUE: "GOSH it was cold in there! I'll help you fight the forces of Death.",
		DIALOG_HOSTAGE_RESCUE: "Thanks for saving me! I'll contribute 500 gold to support you in town.",

		DIALOG_WELL: "The well is filled with fresh water. Come, wash your face!",
		DIALOG_TAVERN: "Welcome to the tavern! Many of my regulars are lost in the dungeons...",

		DIALOG_TOWNSFOLK: [
			"A scary monster in the sewer tried to give me a hug... on my face!",
			"Are you about to attempt a crypt run?",
			"Have you seen my cat?",
			"Have you seen the museum? It used to have some really great exhibits.",
			"I love playing sportsball!",
			"In the cemetery, man-eating plants vomit the skulls of digested corpses. Gross!",
			"Once upon a time, liches used to wander the cemetery...!",
			"Want to play a game?",
			"I broke my arm... too bad I lost my cast.",
			"I could talk about games all day.",
			"Discounts at shops? You wish!",
			"I wish I could wear more than one magic ring, but their magic cancels each other out.",
			"I've heard that white owls are very protective of their kin.",
			"Barrels are often used to hide valuable items.",
			"Did you know that axes get stronger when they bounce?",
			"Not everything is as it seems in the sewer. Even the puddles of goo are dangerous!",
			"Owls will generally leave you alone, but if provoked, they'll rush you.",
			"Shovels aren't great weapons but they can be useful tools, especially in the sewer.",
			"There's a particular grave in the grid of tombstones that gives me the creeps... it's very cold there.",
			"Treasure chests are sometimes actually monsters in disguise.",
			"Aaargh!! A freaking walking talking lizard!! AAaaaarRRrrGGgGhHhh!!!",
			"My Uncle Kenny damaged his elbow trying to use a Boom Spear.",
			"Why does everything seem so familiar?",
			"Who put this here? What were they thinking?!",
			"I was hoping you'd have something more interesting to say.",
			"Why do you throw your weapons? Real warriors get up close and personal!"
		],

		DIALOG_BOOKSHELVES: [
			"The books are covered with cobwebs. Does anyone read anymore?",
			"Books about linear algebra, physics, and trigonometry.",
			"The Seven Habits of Highly Effective Rogues, and other books.",
			"There's Always Money in the Banana Stand, and other books.",
			"How to Train Your Goblin, and other books.",
			"Larry Cotter and the Wizard's Wharf, and other books.",
			"Overcoming Anxiety by Nephthys, and other books.",
			"Chasing Lights by Toes, and other books.",
			"Meowing for Fun and Profit by Loki, and other books.",
			"The Belly Trap by Mojito, and other books.",
			"This Should Be Easier to Use by Andraconda, and other books.",
			"Who Moved My Cat Food? by Lunchbox, and other books.",
			"Cupcakes and Science by Macaronee, and other books.",
			"Arcane Optimizations by Gosub, and other books.",
			"Tablet Wizardry by richtaur, and other books.",
			"A Decade Lost by Maff Blackett, and other books.",
			"Xam's Arena Survival Guide, and other books.",
			"The Care and Feeding of Lunch Bugs, and other books.",
			"The Unwritten Novel by Nadir Safai",
			"Ouch! Papercut.",
			"How to turn a side-scrolling platformer into a strategy RPG, and other books.",
			"How to unintentionally develop a slow-follow to a hit indie game, and other books.",
			"The Lava Blade, and other books."
		],

		DIALOG_INTRO_WIZARD_1: "Ah, Raga! You are just in time, my friend.",
		DIALOG_INTRO_WIZARD_2: "I'm about to finish this magic potion. It will protect us from death!",
		DIALOG_INTRO_WIZARD_3: "Bahahaha, we've done it! With this magic potion, we've mastered death!",

		DIALOG_INTRO_DEATH_1: "So... you dare lay claim over my domain?",

		DIALOG_INTRO_WIZARD_7: "Death! You no longer have any power over us!",

		DIALOG_INTRO_DEATH_2: "SILENCE! Death is far from the worst thing that can happen to you, mortal.",
		DIALOG_INTRO_DEATH_3: "Come to my Crypt and I will show you my meaning.",

		DIALOG_INTRO_TOWNSFOLK_1: [
			"Raga, hello little one ... what happened to your master, the Wizard?",
			"Oh no! ... wait, YOU want to save him? Well, alright... He'll be at Death's Crypt...",
			"It's dangerous to-- oh, just take my stuff!"
		],
		DIALOG_INTRO_TOWNSFOLK_2: "Death has cast a curse on us. The museum's precious artifacts are now lost in the constantly-changing dungeon mazes. Check back here to see your accomplishments.",
		DIALOG_INTRO_TOWNSFOLK_3: "You want to save the Wizard? Head south and talk to the townspeople.",
		DIALOG_INTRO_TOWNSFOLK_4: "Several of the townsfolk went into the Cemetery to rescue the Wizard. I fear they might not come back. Please go after them!",
		DIALOG_INTRO_TOWNSFOLK_5: "To start your journey, head east to the Cemetery. Be careful, Raga.",

		DIALOG_END_WIZARD_1: "Raga? It is you! I was beginning to think I'd never see you or Amberfall again.",
		DIALOG_END_WIZARD_2: "You've certainly come a long way. I knew you had the warrior spirit within you, Raga.",
		DIALOG_END_WIZARD_2B: "You're certainly beat up, Raga. Looks like the potion of life is working!",
		DIALOG_END_WIZARD_3: "Come, my friend. Let's go home.",
		DIALOG_END_WIZARD_1_WIZ: "I must say, this is unexpected.",
		DIALOG_END_WIZARD_2_WIZ: "Could it be that spacetime is cyclical?",
		DIALOG_END_WIZARD_2_WIZB: "Is this what happens to me when I die?",
		DIALOG_END_WIZARD_1_WHO: "Brave warrior, thank you for saving me from Death.",
		DIALOG_END_WIZARD_2_WHO: "Please, take me home to my lizard friend.",

		DIALOG_MERCHANT: "Sorry, I only give discounts to my best customers. Maybe someone in town can help you out...",
		DIALOG_MERCHANT_TOWN: "Welcome to my humble store! We have %s out of %s blueprints in stock. Visit my cousin Boryu in the dungeons to buy more blueprints.",
		DIALOG_BLUEPRINT_SHOP: "Welcome! Buy a blueprint and you'll be able to purchase the new item in Amberfall.",
		DIALOG_TOWN_SHOP_KEEPER: "Soul Power increases Soul Blast and revival strength. Good for those who fight like Wizards!",
		DIALOG_BLUEPRINT_EMPTY: "You've purchased all my blueprints, check another store! You're my favorite customer.",
		DIALOG_GAMBLE_SHOP: "Buy a key to unlock a chest. Who knows what may be inside?!",
		DIALOG_MERCHANT_SKYROCKET: "You's wanna buy some fireworks?",

		DIALOG_STARTING_GOLD_1: "Please take this %s gold, it's all we have but it should help you on your journey.",
		DIALOG_STARTING_GOLD_2: "Rescue more townsfolk in the dungeons to increase your starting gold.",

		ITEM_ABACUS: "Abacus",
		ITEM_APPLE: "Apple",
		ITEM_BREAD: "Sourdough Loaf",
		ITEM_BLUE_CANDLE: "Blue Candle",
		ITEM_COMPASS: "Dungeon Compass",
		ITEM_COOKED_MEAT: "Cooked Meat",
		ITEM_CUPCAKE: "Melissa's Cupcake",
		ITEM_ELIXIR: "Elixir of Life",
		ITEM_FEATHER: "Feather of Flying",
		ITEM_FIRE_STAFF: "Fire Staff",
		ITEM_BLUE_BLAST: "Essence of the Wolf",
		ITEM_GOLD_CART: "Gold Cartridge",
		ITEM_KEY: "Key",
		ITEM_GREEN_KEY: "Slime Key",
		ITEM_DEN_KEY: "Den Key",
		ITEM_DETOX: "Detox",
		ITEM_HEALTH_POTION: "Health Potion",
		ITEM_IVORY_PLATE: "Ivory Plate",
		ITEM_LANTERN: "Lantern",
		ITEM_SKYROCKET: "Skyrocket",
		ITEM_SPIKED_LANTERN: "Spiked Lantern",
		ITEM_LEAD_HEAD: "Dark Iron Helmet",
		ITEM_LEAD_CHEST: "Dark Iron Chestplate",
		ITEM_LEAD_HANDS: "Dark Iron Gauntlets",
		ITEM_LEAD_BOOTS: "Dark Iron Boots",
		ITEM_LEAD_FINGER: "Dark Iron Ring",
		ITEM_WOOD_HELMET: "Heretic Helm",
		ITEM_MITHRIL_MAIL: "Mithril Mail",
		ITEM_ELVISH_TUNIC: "Elven Tunic",
		ITEM_VAMPIRE_CROWN: "Dark Wizard Crown",
		ITEM_MAP: "Dungeon Map",
		ITEM_MONSTER_MANUAL: "Monster Manual",
		ITEM_SELF_IMPROVEMENT: "Book of Totems",
		ITEM_MAGIC_BOOK: "Book of Magic",
		ITEM_BYB: "Book of Totemic Mastery",
		ITEM_SOUL_ORB: "Soul Orb",
		ITEM_SOUL_BLAST: "Soul Blast",
		ITEM_SOUL_SHIELD: "Soul Shield",
		ITEM_SOUL_WARP: "Soul Warp",
		ITEM_SOUL_CALL: "Soul Call",
		ITEM_SOUL_RUSH: "Soul Rush",
		ITEM_ORANGE: "Orange",
		ITEM_DEMON_KEY: "Trickster Key",
		ITEM_ICE_KEY: "Ice Key",
		ITEM_RED_KEY: "Blood Key",
		ITEM_RAW_MEAT: "Raw Meat",
		ITEM_FROZEN_BANANA: "Frozen Banana",

		ITEM_AXE: "Battle Axe",
		ITEM_BOOMERANG: "Boomerang",
		ITEM_BOOMERANG_2: "Magic Boomerang",
		ITEM_GLAIVE: "Glaive",
		ITEM_BOOM_SPEAR: "Boom Spear",
		ITEM_OWLSLAYER: "Owlslayer",
		ITEM_DUAL_DAGGERS: "Dual Daggers",
		ITEM_ROYAL_DAGGER: "Royal Daggers",
		ITEM_SCYTHE: "Scythe",
		ITEM_GOLDEN_AXE: "Golden Axe",
		ITEM_HEAT_AXE: "Heat Axe",
		ITEM_DEMON_AXE: "Trickster Axe",
		ITEM_DEMON_DAGGERS: "Trickster Daggers",
		ITEM_DEMON_SPEAR: "Trickster Spear",
		ITEM_DEMON_SWORD: "Trickster Sword",
		ITEM_ICE_SWORD: "Ice Sword",
		ITEM_IRONSWORD: "Ironsword",
		ITEM_KILLER_BEES: "Killer Bees",
		ITEM_LANCE: "Arthur's Lance",
		ITEM_LAVA_BLADE: "Lava Blade",
		ITEM_LAVA_DAGGER: "Lava Dagger",
		ITEM_LIFE_KNIFE: "Life Knife",
		ITEM_POISON_SWORD: "Poison Sword",
		ITEM_SHOVEL: "Shovel",
		ITEM_SLOWRD: "Slowrd",
		ITEM_SPEAR: "Hunting Spear",
		ITEM_STEEL_BALL: "Steel Ball",
		ITEM_SWORD: "Steel Sword",
		ITEM_TRIDENT: "Trident",
		ITEM_TRIPLE_DAGGER: "Triple Daggers",

		ITEM_FIRE_RING: "Ring of Fire Defense",
		ITEM_ICE_RING: "Ring of Ice Defense",
		ITEM_ANTIFREEZE_RING: "Antifreeze Ring",
		ITEM_FIREPROOF_GLOVES: "Fireproof Gloves",
		ITEM_POISON_RING: "Antivenom Ring",
		ITEM_RIBBON_RING: "Ring of Ultimate Protection",

		ITEM_ARMOR_HEAD: "Shaman Helm",
		ITEM_ARMOR_CHEST: "Shaman Tunic",
		ITEM_ARMOR_HANDS: "Shaman Gloves",
		ITEM_ARMOR_FEET: "Shaman Boots",
		ITEM_ARMOR_FINGER: "Shaman Ring",
		ITEM_ARMOR_HEAD_2: "Wizard's Hat",
		ITEM_ARMOR_CHEST_2: "Wizard's Robes",
		ITEM_ARMOR_HANDS_2: "Wizard's Gloves",
		ITEM_ARMOR_FEET_2: "Wizard's Shoes",
		ITEM_ARMOR_FINGER_2B: "Wizard's Ring",
		ITEM_ARMOR_FINGER_2: "Multi-strike Ring",
		ITEM_SPEED_HEAD: "Hat of Speed",
		ITEM_SPEED_CHEST: "Tunic of Speed",
		ITEM_SPEED_HANDS: "Gloves of Speed",
		ITEM_SPEED_FEET: "Winged Shoes of Speed",
		ITEM_SPEED_FINGER: "Ring of Speed",
		ITEM_ATTACK_HEAD: "Spiked Helm",
		ITEM_ATTACK_CHEST: "Spiked Plate",
		ITEM_ATTACK_HANDS: "Spiked Gauntlets",
		ITEM_ATTACK_FEET: "Spiked Boots",
		ITEM_ATTACK_FINGER: "Spiked Ring",

		ITEM_DEMON_HEAD: "Trickster Head",
		ITEM_DEMON_CHEST: "Trickster Torso",
		ITEM_DEMON_HANDS: "The Trickster Touch",
		ITEM_DEMON_FEET: "Trickster Treads",
		ITEM_DEMON_FINGER: "Trickster Circle",

		ITEM_404: "This spot reserved for a mysterious artifact.",

		ITEM_SOUL_TOTEM: "Soul Totem",
		ITEM_EARTH_TOTEM: "Earth Totem",
		ITEM_ICE_TOTEM: "Ice Totem",
		ITEM_POISON_TOTEM: "Poison Totem",
		ITEM_FIRE_TOTEM: "Fire Totem",
		ITEM_LIGHT_TOTEM: "Light Totem",
		ITEM_BOMB_TOTEM: "Explosive Totem",
		ITEM_COPYCAT_TOTEM: "Copycat Totem",
		ITEM_SWING_TOTEM: "Warlord Totem",
		ITEM_SPEAR_TOTEM: "Huntotem",
		ITEM_HIVE_TOTEM: "Hive Totem",
		ITEM_DAGGER_TOTEM: "Assassin's Totem",
		ITEM_WAVE_TOTEM: "Wave Totem",

		ITEM_ATTACK_CHARM: "Charm of Offense",
		ITEM_HEALTH_CHARM: "Charm of Stamina",
		ITEM_TOTEM_CHARM: "Charm of Totemic Power",
		ITEM_SPEED_CHARM: "Charm of Haste",
		ITEM_MAGIC_CHARM: "Charm of Magic",

		// Custom item descriptions
		ITEM_DESC_MAP: "Reveals the dungeon layout",
		ITEM_DESC_COMPASS: "Reveals the locations of important rooms",
		ITEM_DESC_ABACUS: "Displays numbers during combat",
		ITEM_DESC_MONSTER_MANUAL: "Displays enemy health",
		ITEM_DESC_KEY: "Opens a lock",
		ITEM_DESC_SOUL_ORB: "Contains trapped souls",
		ITEM_DESC_SOUL_TOTEM: "Blasts enemies with undead magic",
		ITEM_DESC_EARTH_TOTEM: "Crushes enemies with rocks",
		ITEM_DESC_ICE_TOTEM: "Freezes enemies",
		ITEM_DESC_POISON_TOTEM: "Poisons enemies",
		ITEM_DESC_BOMB_TOTEM: "Explodes",
		ITEM_DESC_FIRE_TOTEM: "Burns enemies with fire",
		ITEM_DESC_LIGHT_TOTEM: "Sears enemies with pure light",
		ITEM_DESC_COPYCAT_TOTEM: "Projects the same weapon as its caster",
		ITEM_DESC_SWING_TOTEM: "Spins a deadly ball of spikes",
		ITEM_DESC_SPEAR_TOTEM: "Quickly throws spears towards its caster",
		ITEM_DESC_HIVE_TOTEM: "Summons a swarm of BEEEEEES",
		ITEM_DESC_WAVE_TOTEM: "Blasts enemies with a powerful wave",
		ITEM_DESC_DAGGER_TOTEM: "Pierces enemies with an onslaught of daggers",
		ITEM_DESC_SOUL_BLAST: "Unleashes a powerful blast of soul power. Consumes a Soul Orb",
		ITEM_DESC_SOUL_SHIELD: "Protects the caster from harm for a limited time. Consumes a Soul Orb",
		ITEM_DESC_SOUL_WARP: "Bends time in the caster's favor. Consumes a Soul Orb",
		ITEM_DESC_SOUL_RUSH: "Launch forward, damaging everything in your path. Consumes a Soul Orb",
		ITEM_DESC_SOUL_CALL: "Calls forth an ally to help slay your enemies. Consumes a Soul Orb",

		ITEM_DESC_SWORD: "Well-balanced",
		ITEM_DESC_POISON_SWORD: "Poisons enemies",
		ITEM_DESC_SLOWRD: "Large and slow",
		ITEM_DESC_ICE_SWORD: "Blade of ice",
		ITEM_DESC_AXE: "Gains power bouncing off walls",
		ITEM_DESC_GOLDEN_AXE: "Converts enemy blood into gold",
		ITEM_DESC_DUAL_DAGGERS: "Fast but weak",
		ITEM_DESC_TRIPLE_DAGGER: "Trio of daggers",
		ITEM_DESC_SPEAR: "Fast with good range",
		ITEM_DESC_BOOM_SPEAR: "Explodes",
		ITEM_DESC_OWLSLAYER: "Super effective against owls. (You're welcome)",
		ITEM_DESC_TRIDENT: "Pierces enemies",
		ITEM_DESC_BOOMERANG: "Collects items and returns",
		ITEM_DESC_BOOMERANG_2: "Collects items and returns",
		ITEM_DESC_GLAIVE: "Deadlier when returning",
		ITEM_DESC_KILLER_BEES: "Swarm of deadly bees",
		ITEM_DESC_IRONSWORD: "Once wielded by a mighty warrior to defeat an evil wizard",
		ITEM_DESC_HEAT_AXE: "Magical weapon of lizard warriors",
		ITEM_DESC_LANCE: "Once wielded by a mighty warrior to defeat demons",
		ITEM_DESC_BLUE_BLAST: "The powerful lifeforce of the wolf",
		ITEM_DESC_LIFE_KNIFE: "A blade whose power doubles when its owner is healthy",
		ITEM_DESC_GOLD_CART: "The elegant weapon of mysterious engineers",
		ITEM_DESC_DEMON_AXE: "A tricky weapon that deals tricky damage",
		ITEM_DESC_DEMON_DAGGERS: "A tricky weapon that deals tricky damage",
		ITEM_DESC_DEMON_SPEAR: "A tricky weapon that deals tricky damage",
		ITEM_DESC_DEMON_SWORD: "A tricky weapon that deals tricky damage",
		ITEM_DESC_SHOVEL: "A useful tool for prying open objects below your feet",
		ITEM_DESC_SKYROCKET: "An explosive, celebratory weapon",
		ITEM_DESC_DEMON_KEY: "Tricksters are known to abduct werewolves",
		ITEM_DESC_ICE_KEY: "Used to open gates of magical ice",

		MONSTER_BAT: "Bat",
		MONSTER_BLOOD_CRYSTAL: "Blood Crystal",
		MONSTER_COCKATRICE: "Cockatrice",
		MONSTER_CUBE: "Gelatinous Cube",
		MONSTER_ICE_CUBE: "Gelatinice Cube",
		MONSTER_CYCLOPS: "Cyclops",
		MONSTER_DEATH: "Death",
		MONSTER_MERCHANT: "Merchant",
		MONSTER_DEMON: "Deminion",
		MONSTER_WHITE_DEMON: "White Deminion",
		MONSTER_DIRE_BAT: "Dire Bat",
		MONSTER_EYEBALL: "Ioi Eye",
		MONSTER_FIRE_ELEMENTAL: "Fire Elemental",
		MONSTER_GHOST: "Gugugughost",
		MONSTER_GHOST2: "Giant's Skull",
		MONSTER_GOBLIN: "Green Goblin",
		MONSTER_GRAVE_ROBBER: "Zombie Grave Robber",
		MONSTER_GREAT_OWL: "Great Owl",
		MONSTER_GREEN_SLIME: "Green Slime",
		MONSTER_HUGGER: "Face Hugger",
		MONSTER_LURKER: "Lurker",
		MONSTER_LURKER2: "Derper",
		MONSTER_LURKER_LAVA: "Lava Lurker",
		MONSTER_MIMIC: "Mimic",
		MONSTER_MINOTAUR: "Minotaur",
		MONSTER_MUCK_MONSTER: "Muck Monster",
		MONSTER_ICE_MONSTER: "Ice Monster",
		MONSTER_MUTANT: "Mutant Zombie",
		MONSTER_OGRE: "Ogre",
		MONSTER_OWL: "Angry Owl",
		MONSTER_PLANT: "Maneater",
		MONSTER_SAPPER: "Kobold Sapper",
		MONSTER_SEWER_HAG: "Sewer Hag",
		MONSTER_SKELETON: "Skeleton",
		MONSTER_SLIME: "Slime",
		MONSTER_SLIME_CRYSTAL: "Slime Crystal",
		MONSTER_STATUE: "Maro's Statue",
		MONSTER_WEREWOLF: "Werewolf",
		MONSTER_WHITE_ZOMBIE: "White Zombie",
		MONSTER_ZOMBIE: "Zombie",
		MONSTER_ZOMBIE_MERCHANT: "Zombie Merchant",
		MONSTER_ZOMBIE_WARLORD: "Zombie Warlord",
		DESCRIPTION_BAT: "A mean little monster of flight.",
		DESCRIPTION_DIRE_BAT: "A more sinister bat that breathes fire!",
		DESCRIPTION_BLOOD_CRYSTAL: "A magical, malevolent entity made of crystallized blood that has infected the town.",
		DESCRIPTION_COCKATRICE: "A mythological flying monster with dangerous, icy breath.",
		DESCRIPTION_CUBE: "A blob of magical, poisonous goo that can hold mysterious treasures.",
		DESCRIPTION_ICE_CUBE: "A block of magical, freezing ice that can hold mysterious treasures.",
		DESCRIPTION_CYCLOPS: "An ancient monster of the arena that hurls bouncing boulders at its prey.",
		DESCRIPTION_DEATH: "Death needs no introduction. Those who don't know Death someday will.",
		DESCRIPTION_DEMON: "An evil creature from the abyss. Launches itself off of walls for additional speed.",
		DESCRIPTION_WHITE_DEMON: "An albino deminion that holds hidden power.",
		DESCRIPTION_EYEBALL: "Gauged from its victims and then mutated with magic, these monsters shoot energy waves at their prey.",
		DESCRIPTION_FIRE_ELEMENTAL: "Chaotic fire beings that love to burn anything that moves.",
		DESCRIPTION_GHOST: "The decapitated heads of executed killers.",
		DESCRIPTION_GHOST2: "The lost heads of evil giants.",
		DESCRIPTION_GOBLIN: "Scavengers, pilferers, and kidnappers. Nasty little creatures.",
		DESCRIPTION_GRAVE_ROBBER: "Grave Robbers who fell to the curse of the zombie. Sometimes still carries its shovel…",
		DESCRIPTION_GREAT_OWL: "A bigger, meaner owl that is highly protective of its kin.",
		DESCRIPTION_GREEN_SLIME: "An evil slime monster that poisons its victims.",
		DESCRIPTION_HUGGER: "Disturbing little creatures that are laid in sticky egg sacks.",
		DESCRIPTION_LURKER: "A dangerous fish-man with territorial issues.",
		DESCRIPTION_LURKER2: "A mutated lurker that attacks anything in the sewer.",
		DESCRIPTION_LURKER_LAVA: "These evil rock monsters want everything to be melted in the lava.",
		DESCRIPTION_MIMIC: "A bizarre species of monster that has evolved to look like a chest to feed on adventurers.",
		DESCRIPTION_MINOTAUR: "Huge beastmen with the heads of bulls.",
		DESCRIPTION_MUCK_MONSTER: "Enchanted puddles of ooze whose magic compels them to attack dungeon delvers.",
		DESCRIPTION_ICE_MONSTER: "Puddles of evil ice that bleed out of an Gelatinice Cube.",
		DESCRIPTION_MUTANT: "Zombies that have been strengthened with mutations.",
		DESCRIPTION_OGRE: "Large, dumb monsters with axes that really just want to be left alone. Can be caught off guard…",
		DESCRIPTION_OWL: "Oversized, dangerous birds that inhabit the cemetery. They rush when provoked.",
		DESCRIPTION_PLANT: "Man-eating plants that vomit the skulls of their devoured victims.",
		DESCRIPTION_SAPPER: "Kobolds that blindly follow orders to destroy any adventurer exploring the crypt.",
		DESCRIPTION_SEWER_HAG: "An evil witch of great power that is very territorial of the sewer.",
		DESCRIPTION_SKELETON: "The ghosts of fallen monsters or warriors.",
		DESCRIPTION_SLIME: "A (semi) intelligent pile of blue glop, only dangerous when provoked.",
		DESCRIPTION_SLIME_CRYSTAL: "A magical, malevolent crystal entity of slime that has infected the town.",
		DESCRIPTION_STATUE: "Statues carved in droves by the great Maro, who hated for her works to be disturbed.",
		DESCRIPTION_WEREWOLF: "Warriors who were cursed with the powers of the wolf.",
		DESCRIPTION_WHITE_ZOMBIE: "An otherworldy zombie whose strange possessions are not of this universe.",
		DESCRIPTION_ZOMBIE: "Unfortunate townsfolk who were cursed by magic that keeps them alive and makes them crave blood.",
		DESCRIPTION_ZOMBIE_MERCHANT: "An unfortunate merchant that has been cursed as a zombie.",
		DESCRIPTION_ZOMBIE_WARLORD: "An evil warlord of old who was cursed as a zombie for his crimes against humanity.",
		MONSTERS_KILLED: "You've killed %s.",
		MONSTER_404: "This spot reserved for a ferocious monster.",
		ITEMS_WON: "You've finished with this item %s times.",

		ZONE_TOWER: "Wizard's Tower",
		ZONE_MUSEUM: "Museum",
		ZONE_TOWN: "Town of Amberfall",
		ZONE_ARENA: "The Arena",
		ZONE_CEMETERY_1: "Cemetery 1",
		ZONE_CEMETERY_2: "Cemetery 2",
		ZONE_CEMETERY_3: "Cemetery 3",
		ZONE_SEWER_1: "Sewer 1",
		ZONE_SEWER_2: "Sewer 2",
		ZONE_SEWER_3: "Sewer 3",
		ZONE_CRYPT_1: "Crypt 1",
		ZONE_CRYPT_2: "Crypt 2",
		ZONE_CRYPT_3: "Crypt 3",
		ZONE_FOREST: "Forest",
		ZONE_DEN: "Den of Thieves",
		ZONE_DEBUG: "Debug",

		MSG_TUT_MOVE: "Move with WASD keys",
		MSG_TUT_MOVE_A: "Move with left analog stick or D-pad",
		MSG_TUT_ATTACK: "Hold down ARROW keys to attack",
		MSG_TUT_ATTACK_A: "Attack with right analog stick",
		MSG_TUT_INTERACT: "Press SPACE to interact",
		MSG_TUT_INTERACT_A: "Press A to interact",
		MSG_TUT_GAMEPAD: "(or use gamepad)",
		MSG_TUT_DASH: "Press shift to dash",
		MSG_TUT_DASH_A: "Press B to dash",
		MSG_TUT_TOTEM: "Press x to place a totem",
		MSG_TUT_TOTEM_A: "Press X to place a totem",
		MSG_TUT_SOUL: "Press z to use Soul Blast",
		MSG_TUT_SOUL_A: "Press Y to use Soul Blast",

		ACH_TITLE_ALIVE: "Still Alive",
		ACH_DESC_ALIVE: "Starting from the Cemetery, exit the Crypt without dying.",
		ACH_TITLE_DEAD: "Play Dead",
		ACH_DESC_DEAD: "Starting from the Cemetery, exit the Crypt without resurrecting.",
		ACH_TITLE_EMPTY: "Empty Handed",
		ACH_DESC_EMPTY: "Without buying anything in town, start from the Cemetery, and exit the Crypt.",
		ACH_TITLE_SPEED: "Speed Run",
		ACH_DESC_SPEED: "Starting from the Cemetery, exit the Crypt in 20 minutes or less.",
		ACH_TITLE_MERCHANTS: "Merchant Murderer",
		ACH_DESC_MERCHANTS: "Kill 12 merchants in one crawl.",
		ACH_TITLE_RESCUE: "Good Samaritan",
		ACH_DESC_RESCUE: "Rescue 3 hostages in one crawl.",
		ACH_TITLE_SOULS: "Soul Hoarder",
		ACH_DESC_SOULS: "Collect 30 Soul Orbs in one crawl.",

		WORN_ON_THE_X: "Equipped to %s",
		MYSTERY_ITEM: "Not much is known about this mysterious item",
		DAMAGE_TAKEN_FROM_X: "Damage taken from %s",

		DAMAGE_TYPE_FIRE: "Fire",
		DAMAGE_TYPE_ICE: "Ice",

		// Slots
		SLOT_HEAD: "Head",
		SLOT_CHEST: "Chest",
		SLOT_HANDS: "Hands",
		SLOT_FEET: "Feet",
		SLOT_FINGER: "Finger",
		SLOT_WEAPON: "Weapon sheath",
		SLOT_TOTEM: "Totem holster",
		SLOT_LIGHT: "Light hook",
		SLOT_BOOK: "Book pouch",
		SLOT_SOUL: "Soul",

		// Stats
		STAT_HEALTH: "Health: %s / %s",
		STAT_SPEED: "Speed",
		STAT_ATTACK: "Attack",
		STAT_MAGIC: "Soul Power",
		STAT_ARMOR: "Armor",
		STAT_PROJECTILECOUNT: "Projectile Count",
		STAT_PROJECTILEVARIANCE: "Projectile Variance",
		STAT_PROJECTILESPREAD: "Projectile Spread",
		STAT_ATTACKCOOLDOWN: "Attack Cooldown",
		STAT_TOTEMPOWER: "Totem Power",
		STAT_ALIGNMENT: "Trickiness",

		random: "Random",
		raga: "Raga",
		moto: "Moto",
		luna: "Luna",
		wizard: "Wizard",
		engineer: "The Engineer"
	}
});
