define({
	code: "pt-br",
	strings: {
		ACHIEVEMENTS: "Conquistas",
		ACHIEVEMENT_EARNED: "Conquistas desbloqueadas! %s",
		AMOUNT_EARNED: "%s / %s desbloqueadas",
		ANALOG_DEAD_ZONE_LEFT: "Dead zone do analógico esquerdo",
		ANALOG_DEAD_ZONE_RIGHT: "Dead zone do analógico direito",
		ARMOR_SHOP: "Loja de armaduras",
		ATTACK_UP: "Atacar para cima",
		ATTACK_LEFT: "Atacar para a esquerda",
		ATTACK_DOWN: "Atacar para baixo",
		ATTACK_RIGHT: "Atacar para a direita",
		BACK: "Voltar",
		BLUEPRINT_X: "Projeto: %s",
		CHALLENGE_CTA: "Copie esta URL e a envie para um amigo para desafia-lo",
		CHALLENGER: "Desafiante",
		CONTINUE: "Continuar",
		CELEBRATE_KILL: "Morto %s %s vezes!",
		CHARACTER_RAGA: "Raga",
		CHARACTER_RAGADARK: "Raga",
		CHARACTER_ENGINEER: "O Engenheiro",
		CHARACTER_WIZARD: "Mago",
		CHARACTER_LUNA: "Luna",
		CHARACTER_MOTO: "Moto",
		COMMISSIONED_BY: "Comissionado por %s",
		COMPLETE: "Completo!",
		COPYRIGHT: "v%s © Lost Decade Games",
		DAMAGE_TAKEN: "Dano recebido",
		DANGER: "Perigo!",
		DARKNESS: "Brilho",
		DASH: "Dash",
		DECREASES_X: "Diminui %s",
		DISABLED: "Desativado",
		DUNGEON_COMPLETE: "%s completo",
		ENABLED: "Ativado",
		EQUIPMENT: "Equipamento",
		FIRST_KILL: "Primeira morte! %s",
		FULLSCREEN: "Tela cheia",
		GAME_OVER: "GAME OVER",
		GAMEPAD_STATUS: "Gamepad: %s",
		GOLD_MONSTER_STATUE_EARNED: "Épico! Você é um mestre em matar %s.",
		GRAND_HALL: "Grande Hall",
		HALL_OF_ARMOR: "Hall da Defesa",
		HALL_OF_PATRONS: "Hall dos Patrões",
		HALL_OF_MONSTERS: "Hall dos Monstros",
		HALL_OF_ITEMS: "Hall dos Artefatos",
		HALL_OF_WEAPONS: "Hall da Guerra",
		HALL_OF_CEMETERY: "Hall dos Túmulos",
		HALL_OF_SEWER: "Hall da Gosma",
		HALL_OF_CRYPT: "Hall dos Mortos",
		HUD_ITEMS_ON: "Desativar inventário",
		HUD_ITEMS_OFF: "Ativar inventário",
		INCOMPLETE: "Incompleto",
		INCREASES_X: "Aumenta o status de %s",
		INPUT_START: "Por favor, aperte A em seu controle",
		INTERACT: "Interagir",
		INVENTORY: "Inventário",
		ITEM_SHOP: "Loja de Itens",
		KEY_BINDINGS: "Configuração de Teclas",
		DELETE_DATA: "Apagar saves",
		DELETE_DATA2: "REALMENTE apagar saves!",
		MARKETPLACE: "Mercado",
		MOVE_UP: "Mover para cima",
		MOVE_LEFT: "Mover para a esquerda",
		MOVE_DOWN: "Move para baixo",
		MOVE_RIGHT: "Move para a direita",
		MUSEUM: "Museu",
		MUSEUM_LAB: "Laboratório do Museu",
		MUSEUM_LIBRARY: "Bibioteca do Museu",
		MUSEUM_LOBBY: "Lobby do Museu",
		MUSEUM_MAIN_HALL: "Hall principal do Museu",
		MUSEUM_MONSTER_HALL: "Hall dos monstros do Museu",
		MUSEUM_WEST_HALL: "Hall oeste do Museu",
		MUSEUM_QUARTERS: "Acomodações do Museu",
		MUSEUM_STOREROOM: "Depósito do Museu",
		MUSIC_ON: "Desativar Música",
		MUSIC_OFF: "Ativar música",
		MUSIC_VOLUME: "Volume da música",
		NEXT: "Próximo",
		NONE: "Nenhum",
		OPTIONS: "Opções",
		PLAY: "Jogar!",
		PLAYER_SELECT: "Selecione um personagem",
		PROGRESS_START: "Derrotar a Morte",
		PRESS_BUTTON: "Aperte qualquer botão frontal do controle",
		TAB_LEFT: "ou pressione [",
		TAB_RIGHT: "ou pressione ]",
		RETURN_TO_TITLE: "Voltar à tela principal",
		RESTART: "Jogar novamente",
		CHARACTER_SELECT: "Seleção de personagems",
		TITLE: "Voltar à tela principal",
		QUIT: "Sair",
		QUIT2: "Realmente sair",
		RESET_TO_DEFAULTS: "Restaurar configurações padrão",
		SETTINGS: "Opções",
		SOUNDS_ON: "Desativar efeitos sonoros",
		SOUNDS_OFF: "Ativar efeitos sonoros",
		SOUND_VOLUME: "Volume dos efeitos sonoros",
		STATUES_EARNED: "Novo monstro morto",
		SWAP_ANALOGS: "Trocar analógicos",
		HOSTAGES_RESCUED: "Cidadãos resgatados",
		TAVERN: "Taverna",
		TOGGLEFULLSCREEN: "Alternar tela cheia",
		TIME: "Tempo",
		TIME_N: "Tempo: %s",
		TREASURE: "Tesouros",
		UPDATE_AVAILABLE: "Atualização disponível - clique aqui",
		USE_SOUL_ORB: "Usar Soul Orb",
		USE_TOTEM: "Usar Totem",
		WEAPON_SHOP: "Loja de Armamento",
		YOU: "Vôce",
		CREDITS: "Creditos",
		MAKERS: "Design & Programação",
		ART: "Arte",
		AUDIO: "Musica & Efeitos sonoros",
		BIZDEV: "Marketing & Divulgação",
		BRONZE_SPONSORS: "Apoiadores de Bronze",
		SILVER_SPONSORS: "Apoiadores de Prata",
		GOLD_SPONSORS: "Apoiadores de Ouro",
		SPECIAL_THANKS: "Agradecimentos especiais",
		THE_END: "Obrigado por jogar A Wizard's Lizard!",
		WINS_LOSSES: "Vitórias: %s, Mortes: %s",
		DIALOG_SEWER_LOCKED: "Esse atalho leva ao esgoto, mas a passagem está bloqueada por cristais misteriosos.",
		DIALOG_SEWER_UNLOCKED: "Parece que você tirou os cristais do caminho, muito bem! O atalho para o esgoto agora está acessível.",
		DIALOG_CRYPT_LOCKED: "Esse atalho leva à Cripta, mas a passagem está bloqueada por cristais misteriosos.",
		DIALOG_CRYPT_UNLOCKED: "Parece que você tirou os cristais do caminho, muito bem! O atalho para a Cripta agora está acessível.",
		DIALOG_ARENA_INFO: "Apenas os guerreiros mais renomados podem testar suas abilidades na Arena. Quando você alcançar %s mortes, poderá entrar. Você matou %s monstros até agora.",
		DIALOG_LUNA_RESCUE: "Ufa, obrigado por me salvar! Eu achei que iria me queimar com toda essa lava... Vou te ajudar a combater a Morte.",
		DIALOG_MOTO_RESCUE: "Grr, eu nasci para lutar. Aqueles demônios me capturaram e agora eu quero VINGANÇA! Grr, Vou te ajudar a combater a Morte.",
		DIALOG_ENGINEER_RESCUE: "NOSSA, tava frio lá! Vou te ajudar a combater a Morte.",
		DIALOG_HOSTAGE_RESCUE: "Obrigado por me resgatar! Eu vou te ajudar com 500 de ouro!",
		DIALOG_WELL: "O poço está cheio de água fresca. Venha, lave seu rosto!",
		DIALOG_TAVERN: "Bem vindo à taverna! Muitos dos meus melhores clientes estão perdidos nas dungeons...",
		DIALOG_TOWNSFOLK: [
			"Um monstro assustador do esgoto tentou abraçar... meu rosto!",
			"Você está prestes a fazer uma Crypt Run?",
			"Você viu meu gato por ai?",
			"Você já foi dar uma olhada no museu? Ele já recebeu exposições muito legais.",
			"Eu amo jogar futebol!",
			"No cemitério existem plantas carnívoras que vomitam os crânios de suas presas. Nojento!",
			"A muito tempo atrás, mortos-vivos costumavam vagar pelo cemitério...!",
			"Quer jogar?",
			"Eu quebrei meu braço... é uma pena que eu tenha perdido meu elenco.",
			"Eu poderia conversar sobre jogos o dia inteiro.",
			"Desconto nas lojas? Só nos seus sonhos!",
			"Eu queria poder usar mais de um anel mágico ao mesmo tempo, mas o poder deles me impede de fazer isso.",
			"Eu ouvi em falar que as corujas brancas são bastante protetoras quando se trata de indivíduos da mesma espécie.",
			"Barris são muitas vezes usados para esconder items valiosos.",
			"Você sabia que machados causam mais dano quando eles quicam?",
			"Nem tudo é o que parece no esgoto. Até poças de gosma são perigosas!",
			"As corujas geralmente te deixam em paz, a não ser que você as provoque. Ai elas vão te perseguir.",
			"Pás não são as melhores armas que existem, mas podem ser ferramentas muito úteis, especialmente no esgoto.",
			"Tem uma lápide em especial no cemitério que me dá arrepios... é muito frio lá.",
			"Baús podem algumas vezes ser monstros muito bem disfarçados.",
			"Aaargh!! Um lagarto falante!! AAaaaarRRrrGGgGhHhh!!!",
			"Meu tio Kenny machucou sua sombramcelha tentando usar uma Lança Explosiva.",
			"Por que tudo parece tão familiar?",
			"Quem colocou isso ai? O que ele estava pensado?!",
			"Eu esperava que você tivesse algo mais interessante a dizer.",
			"Por que você joga suas armas? Guerreiros de verdade combatem seus inimigos corpo a corpo!"
		],
		DIALOG_BOOKSHELVES: [
			"Os livros estão cobertos por teias de aranha. Será que ninguem mais lê hoje em dia?",
			"Livros sobre algebra linear, física, e trigonometria.",
			"Os Sete Hábitos de Ladrões Muito eficientes, e outros livros.",
			"Sempre tem Dinheiro no porta-bananas, e outros livros.",
			"Como Treinar seu Goblin, e outros livros.",
			"Larry Cotter e o Cais do Mago, e outros livros.",
			"Superando a Ansiedade, de Nephthys, e outros livros.",
			"Correndo atrás da Luz, de Toes, e outros livros.",
			"Miando como hobby e profissão, de Loki, e outros livros.",
			"A armadilha do Umbigo, de Mojito, e outros livros.",
			"Isso Deveria ser mais fácil de Usar, de Andraconda, e outros livros.",
			"Quem Tirou a comida do Meu gato do Lugar?, de Lunchbox, e outros livros.",
			"A ciência dos Cupcakes, de Macaronee, e outros livros.",
			"Otimização Arcana, de Gosub, e outros livros.",
			"A magia dos Tablets, de richtaur, e outros livros.",
			"Uma década perdida, de Maff Blackett, e outros livros.",
			"O guia do Xam para a sobrevivência na Arena, e outros livros.",
			"Cuidados e Alimentação para Lunch Bugs, e outros livros.",
			"A novela não escrita, de Nadir Safai",
			"Ai! Cortei minha mão com papel.",
			"Como transformar um jogo de Plataforma em um RPG de estratégia, e outros livros.",
			"Como não-intencionalmente desenvolver uma sequência ruim para um jogo indie de sucesso, e outros livro.",
			"A espada de Lava, e outros livros."
		],
		DIALOG_INTRO_WIZARD_1: "Raga! Você chegou na hora certa meu amiguinho.",
		DIALOG_INTRO_WIZARD_2: "Eu estou quase terminando essa poção mágica. Ela vai nos proteger da morte!",
		DIALOG_INTRO_WIZARD_3: "Bahahaha, nós conseguimos! Com essa poção mágica, nós dominamos a morte!",
		DIALOG_INTRO_DEATH_1: "Você ousa tomar o que é de meu domínio?",
		DIALOG_INTRO_WIZARD_7: "Morte! Não adianta, você não tem mais poder sobre nós!",
		DIALOG_INTRO_DEATH_2: "CALADO! A morte está longe de ser a pior coisa que pode acontecer a você, mortal.",
		DIALOG_INTRO_DEATH_3: "Venha à minha Cripta, e te mostrarei o que quero dizer.",
		DIALOG_INTRO_TOWNSFOLK_1: ["Raga, e ai baixinho ... o que aconteceu com o seu mestre, o mago?", "Ah não! ... espere, VOCÊ quer salvá-lo? Bem, tá bom então... Ele estará na Cripta da Morte...", "É perigoso ir sozinho... Ah, so pegue essas coisas!"],
		DIALOG_INTRO_TOWNSFOLK_2: "A morte jogou um feitiço sobre nós. Os preciosos artefatos pertencentes ao museu agora estão espalhados por labirintos constantemente mudando. Venha aqui quando você quiser checar quantos deles você achou.",
		DIALOG_INTRO_TOWNSFOLK_3: "Você quer salvar o Mago? Bom, vá para o sul e fale com as pessoas por lá.",
		DIALOG_INTRO_TOWNSFOLK_4: "Vários dos habitantes do vilarejo foram tentar salvar o Mago. Eu temo que eles não voltem... Por favor, vá atrás deles!",
		DIALOG_INTRO_TOWNSFOLK_5: "Para começar sua jornada, vá para o leste, em direção ao Cemetério. Seja cuidadoso, Raga.",
		DIALOG_END_WIZARD_1: "Raga? É você! Eu já estava pensando que nunca veria você ou Amberfall novamente.",
		DIALOG_END_WIZARD_2: "Você certamente teve uma longa jornada. Eu sempre soube que você tinha um espírito guerreiro, Raga.",
		DIALOG_END_WIZARD_2B: "Você está certamente machucado, Raga. Parece que a poção está funcionando!",
		DIALOG_END_WIZARD_3: "Venha, meu amigo. Vamos para casa.",
		DIALOG_END_WIZARD_1_WIZ: "Eu tenho de adimitir, isso foi inesperado.",
		DIALOG_END_WIZARD_2_WIZ: "Talvez o tempo-espaço seja um ciclo?",
		DIALOG_END_WIZARD_2_WIZB: "Isso é o que acontece quando eu morro?",
		DIALOG_END_WIZARD_1_WHO: "Bravo guerreiro, obrigado por salvar-me da Morte.",
		DIALOG_END_WIZARD_2_WHO: "Por favor, me leve para casa, junto de meu amigo, Raga.",
		DIALOG_MERCHANT: "Desculpe, eu só dou descontos para os meus melhores clientes. Talvez alguém na cidade possa te ajudar...",
		DIALOG_MERCHANT_TOWN: "Bem vindo à minha humilde loja! Nós temos %s de %s diferentes items no estoque. Visite meu primo Boryu nas dungeons para comprar mais projetos de items.",
		DIALOG_BLUEPRINT_SHOP: "Bem vindo! Compre um projeto, e você poderá comprar o item correspondente em Amberfall.",
		DIALOG_TOWN_SHOP_KEEPER: "O Soul Power aumenta o dano do Soul Blast e a sua saúde ao ressucitar. Bom para aqueles que lutam como magos!",
		DIALOG_BLUEPRINT_EMPTY: "Você comprou tudo o que eu tinha, dê uma olhada em outra loja! Você é meu melhor cliente.",
		DIALOG_GAMBLE_SHOP: "Compre uma chava para abrir um baú. O que será que estará dentro dele?!",
		DIALOG_STARTING_GOLD_1: "Por favor, pegue essa quantia de %s em ouro. É tudo que nós temos, mas deve te ajudar em sua jornada.",
		DIALOG_STARTING_GOLD_2: "Resgate mais cidadãos de Amberfall para ter mais ouro inicial.",
		ITEM_ABACUS: "Ábaco",
		ITEM_APPLE: "Maça",
		ITEM_BREAD: "Pão Levedo",
		ITEM_BLUE_CANDLE: "Vela azul",
		ITEM_COMPASS: "Bússola do Labirinto",
		ITEM_COOKED_MEAT: "Carne cozida",
		ITEM_CUPCAKE: "Cupcake da Melissa",
		ITEM_ELIXIR: "Elixir da Vida",
		ITEM_FEATHER: "Pena de Voo",
		ITEM_FIRE_STAFF: "Cajado do Fogo",
		ITEM_BLUE_BLAST: "Essência do Lobo",
		ITEM_GOLD_CART: "Cartucho dourado",
		ITEM_KEY: "Chave",
		ITEM_GREEN_KEY: "Chave de Lodo",
		ITEM_DEN_KEY: "Chave do Covil",
		ITEM_DETOX: "Desentoxicador",
		ITEM_HEALTH_POTION: "Poção de Vida",
		ITEM_IVORY_PLATE: "Armadura de Marfim",
		ITEM_LANTERN: "Lanterna",
		ITEM_SPIKED_LANTERN: "Lanterna Espinhuda",
		ITEM_LEAD_BOOTS: "Botas de couro",
		ITEM_LEAD_CHEST: "Peitoral de Couro",
		ITEM_WOOD_HELMET: "Capacete Herege",
		ITEM_MITHRIL_MAIL: "Cota de malha de Mithril",
		ITEM_ELVISH_TUNIC: "Túnica Élfica",
		ITEM_VAMPIRE_CROWN: "Coroa Vampírica",
		ITEM_MAP: "Mapa do Labirinto",
		ITEM_MONSTER_MANUAL: "Manual dos Monstros",
		ITEM_SELF_IMPROVEMENT: "Manual dos Totems",
		ITEM_MAGIC_BOOK: "Manual da Magia",
		ITEM_BYB: "Guia da maestria dos Totems",
		ITEM_SOUL_ORB: "Soul Orb",
		ITEM_ORANGE: "Laranja",
		ITEM_DEMON_KEY: "Chave demoníaca",
		ITEM_RED_KEY: "Chave de Sangue",
		ITEM_RAW_MEAT: "Carne Crua",
		ITEM_AXE: "Machado de Batalha",
		ITEM_BOOMERANG: "Bumerangue",
		ITEM_BOOMERANG_2: "Bumerangue Mágico",
		ITEM_BOOM_SPEAR: "Lança Explosiva",
		ITEM_DUAL_DAGGERS: "Punhal Duplo",
		ITEM_ROYAL_DAGGER: "Punhal Real",
		ITEM_SCYTHE: "Gadanha",
		ITEM_GOLDEN_AXE: "Machado de Ouro",
		ITEM_HEAT_AXE: "Machado do Calor",
		ITEM_DEMON_SWORD: "Espada demoníaca",
		ITEM_ICE_SWORD: "Espada de Gelo",
		ITEM_IRONSWORD: "Espada de Ferro",
		ITEM_KILLER_BEES: "Abelhas Assassinas",
		ITEM_LANCE: "Lança de Arthur",
		ITEM_LAVA_BLADE: "Espada de Lava",
		ITEM_LAVA_DAGGER: "Lava Dagger",
		ITEM_LIFE_KNIFE: "Faca da Vida",
		ITEM_SHOVEL: "Pá",
		ITEM_SLOWRD: "Devaspada",
		ITEM_DEMON_SPEAR: "Lança demoníaca",
		ITEM_SPEAR: "Lança de Caça",
		ITEM_STEEL_BALL: "Bola de Aço",
		ITEM_SWORD: "Espada de Aço",
		ITEM_TRIDENT: "Tridente de Poseidon",
		ITEM_TRIPLE_DAGGER: "Punhal Triplo",
		ITEM_FIRE_RING: "Anel da defesa contra Fogo",
		ITEM_ICE_RING: "Anel da defesa contra Gelo",
		ITEM_ANTIFREEZE_RING: "Anel anti-congelamento",
		ITEM_FIREPROOF_GLOVES: "Luvas a prova de fogo",
		ITEM_POISON_RING: "Anel anti-veneno",
		ITEM_POISON_SWORD: "Espada Venenosa",
		ITEM_ARMOR_HEAD: "Capacete de Shaman",
		ITEM_ARMOR_CHEST: "Túnica de Shaman",
		ITEM_ARMOR_HANDS: "Luvas de Shaman",
		ITEM_ARMOR_FEET: "Botas de Shaman",
		ITEM_ARMOR_FINGER: "Anel de Destreza",
		ITEM_ARMOR_HEAD_2: "Capacete de Battle-Mage",
		ITEM_ARMOR_CHEST_2: "Peitoral de Battle-Mage",
		ITEM_ARMOR_HANDS_2: "Manoplas de Battle-Mage",
		ITEM_ARMOR_FEET_2: "Botas de Battle-Mage",
		ITEM_ARMOR_FINGER_2: "Anel de multi-projétil",
		ITEM_SPEED_HEAD: "Boné de Guardião da Floresta",
		ITEM_SPEED_CHEST: "Túnica de Guardião da Floresta",
		ITEM_SPEED_HANDS: "Luvas de Guardião da Floresta",
		ITEM_SPEED_FEET: "Botas de Guardião da Floresta",
		ITEM_SPEED_FINGER: "Anel de velocidade secundária",
		ITEM_ATTACK_HEAD: "Capacete Espinhudo",
		ITEM_ATTACK_CHEST: "Peitoral Espinhudo",
		ITEM_ATTACK_HANDS: "Manoplas Espinhudas",
		ITEM_ATTACK_FEET: "Botas Espinhudas",
		ITEM_ATTACK_FINGER: "Anel de Agressão",
		ITEM_DEMON_HEAD: "Crânio do Demõnio",
		ITEM_DEMON_CHEST: "Peitoral Demoníaco",
		ITEM_DEMON_HANDS: "Luvas Demoníacas",
		ITEM_DEMON_FEET: "Cascos de Demônio",
		ITEM_DEMON_FINGER: "Anel Demoníaco",
		ITEM_404: "Esse lugar está reservado para um artefato misterioso.",
		ITEM_SOUL_TOTEM: "Totem das Almas",
		ITEM_EARTH_TOTEM: "Totem da Terra",
		ITEM_ICE_TOTEM: "Totem do Gelo",
		ITEM_POISON_TOTEM: "Totem do Veneno",
		ITEM_FIRE_TOTEM: "Totem do Fogo",
		ITEM_LIGHT_TOTEM: "Totem da Luz",
		ITEM_BOMB_TOTEM: "Totem Explosivo",
		ITEM_RADIUS_CHARM: "Encatamento de Alcance Totêmico",
		ITEM_DURATION_CHARM: "Ecantamento de Saúde Totêmica",
		ITEM_EFFECT_CHARM: "Encantamento de Poder Totêmico",
		ITEM_COOLDOWN_CHARM: "Encantamento de Velocidade Totêmica",
		ITEM_DESC_MAP: "Revela o formato da dungeon",
		ITEM_DESC_COMPASS: "Revela a localização de salas importantes",
		ITEM_DESC_ABACUS: "Mostra números de combate",
		ITEM_DESC_MONSTER_MANUAL: "Mostra a vida dos inimigos",
		ITEM_DESC_KEY: "Abre uma fechadura",
		ITEM_DESC_SOUL_ORB: "COntém almas aprisionadas",
		ITEM_DESC_SOUL_TOTEM: "Atinge inimigos com magia",
		ITEM_DESC_EARTH_TOTEM: "Esmaga inimigos com rochas",
		ITEM_DESC_ICE_TOTEM: "Congela os inimigos",
		ITEM_DESC_POISON_TOTEM: "Envenena os inimigos",
		ITEM_DESC_BOMB_TOTEM: "Explode",
		ITEM_DESC_FIRE_TOTEM: "Queima inimigos com fogo",
		ITEM_DESC_LIGHT_TOTEM: "Cauteriza inimigos com poder santo",
		ITEM_DESC_SWORD: "Balanceada",
		ITEM_DESC_POISON_SWORD: "Envenena inimigos",
		ITEM_DESC_SLOWRD: "Devagar e grande",
		ITEM_DESC_ICE_SWORD: "Tem uma lâmina feita de gelo",
		ITEM_DESC_AXE: "Quica",
		ITEM_DESC_GOLDEN_AXE: "Transforma sangue de inimigos em ouro",
		ITEM_DESC_DUAL_DAGGERS: "Rápidas mas fracas",
		ITEM_DESC_ROYAL_DAGGER: "Causa danos críticos",
		ITEM_DESC_TRIPLE_DAGGER: "Trio de punhais",
		ITEM_DESC_SPEAR: "Rápida e com grande alcance",
		ITEM_DESC_BOOM_SPEAR: "Explode",
		ITEM_DESC_TRIDENT: "Perfura os inimigos",
		ITEM_DESC_BOOMERANG: "Coleta items e volta em direção ao atacante",
		ITEM_DESC_BOOMERANG_2: "Coleta items e volta em direção ao atacante",
		ITEM_DESC_KILLER_BEES: "Enxame de abelhas mortíferas",
		MONSTER_BAT: "Morcego",
		MONSTER_BLOOD_CRYSTAL: "Cristal de Sangue",
		MONSTER_COCKATRICE: "Cocatrice",
		MONSTER_CUBE: "Cubo Gelatinoso",
		MONSTER_ICE_CUBE: "Cubo Congelante",
		MONSTER_CYCLOPS: "Ciclope",
		MONSTER_DEATH: "Morte",
		MONSTER_MERCHANT: "Mercador",
		MONSTER_DEMON: "Lacaiônio",
		MONSTER_WHITE_DEMON: "Lacaiônio Branco",
		MONSTER_DIRE_BAT: "Morcego Medonho",
		MONSTER_EYEBALL: "Olho de Ioi",
		MONSTER_FIRE_ELEMENTAL: "Elemental de Fogo",
		MONSTER_GHOST: "Fantaaaaaasma",
		MONSTER_GHOST2: "Caveira Gigantesca",
		MONSTER_GOBLIN: "Goblin Verde",
		MONSTER_GRAVE_ROBBER: "Ladrão de túmulos zumbi",
		MONSTER_GREAT_OWL: "Grande Coruja",
		MONSTER_GREEN_SLIME: "Slime Verde",
		MONSTER_HUGGER: "Abraça-Rosto",
		MONSTER_LURKER: "Espreiteiro",
		MONSTER_LURKER2: "Derper",
		MONSTER_LURKER_LAVA: "Espreiteiro de Lava",
		MONSTER_MIMIC: "Disfarçador",
		MONSTER_MINOTAUR: "Minotauro",
		MONSTER_MUCK_MONSTER: "Monstro de Gosma",
		MONSTER_ICE_MONSTER: "Monstro de Gelo",
		MONSTER_MUTANT: "Zumbi Mutante",
		MONSTER_OGRE: "Ogro",
		MONSTER_OWL: "Coruja Raivosa",
		MONSTER_PLANT: "Planta Carnivora",
		MONSTER_SAPPER: "Sapador Koboldo",
		MONSTER_SEWER_HAG: "Feiticeira do Esgoto",
		MONSTER_SKELETON: "Esqueleto",
		MONSTER_SLIME: "Slime",
		MONSTER_SLIME_CRYSTAL: "Cristal de Lodo",
		MONSTER_STATUE: "Estátua do Maro",
		MONSTER_WEREWOLF: "Lobisomem",
		MONSTER_WHITE_ZOMBIE: "Zumbi Branco",
		MONSTER_ZOMBIE: "Zumbi",
		MONSTER_ZOMBIE_MERCHANT: "Mercador Zumbi",
		MONSTER_ZOMBIE_WARLORD: "Caudilho Zumbi",
		DESCRIPTION_BAT: "Um malvado monstro voador.",
		DESCRIPTION_DIRE_BAT: "Um morcego um pouco mais sinistro, que cospe fogo!",
		DESCRIPTION_BLOOD_CRYSTAL: "Uma entidade mágica e malévola feita de sangue cristalizado, que infectou o vilarejo.",
		DESCRIPTION_COCKATRICE: "Um mitológico monstro voador, com bafo congelante.",
		DESCRIPTION_CUBE: "Uma mágica gosma venenosa que pode conter tesouros misteriosos.",
		DESCRIPTION_ICE_CUBE: "Um bloco mágico de gelo que pode conter tesouros misteriosos.",
		DESCRIPTION_CYCLOPS: "Um antigo mostro da arena que lança pedras como forma de ataque.",
		DESCRIPTION_DEATH: "A morte não precisa de apresentação. Os que não a conhecem um dia conhecerão.",
		DESCRIPTION_DEMON: "Uma malévola criatura vinda do abismo. Se atira das parede para ter velocidade extra.",
		DESCRIPTION_WHITE_DEMON: "Um demônio albino detentor de um poder secreto.",
		DESCRIPTION_EYEBALL: "Arrancados de suas vítimas e então mutados com magia, esse monstros lançam ondas de energia como forma de ataque.",
		DESCRIPTION_FIRE_ELEMENTAL: "Seres caóticos feitos de fogo que adoram queimar qualquer coisa que se mova.",
		DESCRIPTION_GHOST: "Cabeças decaptadas de assassinos mortos.",
		DESCRIPTION_GHOST2: "Os crânios perdidos de gigantes malfeitores.",
		DESCRIPTION_GOBLIN: "Necrófagos, larápios e sequestradores. Criaturinhas desagradáveis.",
		DESCRIPTION_GRAVE_ROBBER: "Ladrões de túmulos que foram atingidos pelo feitiço dos zumbis. Alguns ainda carregam suas pás…",
		DESCRIPTION_GREAT_OWL: "Uma coruja maior e mais desagradável, que é muito protetora para com suas companheiras.",
		DESCRIPTION_GREEN_SLIME: "Um monstro de lodo que envenena suas vítimas.",
		DESCRIPTION_HUGGER: "Criaturinhas perturbadoras que são deixadas por suas mães em casúlos ovais.",
		DESCRIPTION_LURKER: "Um perigoso homem-peixe com alguns problemas territoriais.",
		DESCRIPTION_LURKER2: "Um homem-peixe mutante que ataca qualquer coisa que vê pela frente.",
		DESCRIPTION_LURKER_LAVA: "Esse malvados monstros de rocha querem ver tudo derreter na lava.",
		DESCRIPTION_MIMIC: "Uma espécie bizarra de monstros que evoluiu para se parecer com um baú.",
		DESCRIPTION_MINOTAUR: "Uma besta com cabeça de touro.",
		DESCRIPTION_MUCK_MONSTER: "Poças de lodo encantadas, cujo feitiço as faz atacar exploradores de dungeons.",
		DESCRIPTION_ICE_MONSTER: "Poças de gelo que derreteram de um cubo de gelo.",
		DESCRIPTION_MUTANT: "Zumbis que tornaram-se mais fortes com mutações.",
		DESCRIPTION_OGRE: "Grandes e burros monstros que só querem ficar sozinho. As vezes podem ser encontrados fora de guarda…",
		DESCRIPTION_OWL: "Gigantescos e perigosos pássaros que habitam o cemitério. Elas correm atrás daqueles que as provocam.",
		DESCRIPTION_PLANT: "Plantas carnívoras que vomitam os crânios de suas presas.",
		DESCRIPTION_SAPPER: "Koboldos que segamente seguem ordens para atacar qualquer aventureiro que se atreva a entrar em uma dungeon.",
		DESCRIPTION_SEWER_HAG: "Uma poderosa e malvada bruxa que costuma aparecer nos esgotos.",
		DESCRIPTION_SKELETON: "Fantasmas de monstros ou guerreiros derrotados.",
		DESCRIPTION_SLIME: "Uma poça de gosma (semi) inteligente. Apenas perigosa quando provocada.",
		DESCRIPTION_SLIME_CRYSTAL: "Uma malevolente entidade de cristal de lodo que infectou o vilarejo.",
		DESCRIPTION_STATUE: "Estátuas esculpidas aos monstes pela grande Maro, que odiava quando interrompiam seu trabalho.",
		DESCRIPTION_WEREWOLF: "Guerreiros que foram amaldiçoados com os poderes do Lobo.",
		DESCRIPTION_WHITE_ZOMBIE: "Um zumbi de outro mundo com posses extra-terrestres.",
		DESCRIPTION_ZOMBIE: "Desafortunados cidadãos de Amberfall que forma amaldiçoados com um feitiço que os mantém vivos e os faz desejar sangue.",
		DESCRIPTION_ZOMBIE_MERCHANT: "Um azarado mercador que recebeu um feitiço que o transformou em um zumbi.",
		DESCRIPTION_ZOMBIE_WARLORD: "Um malvado caudilho que foi transformado em um zumbi como punição por seus crimes contra a humanidade.",
		MONSTERS_KILLED: "Você matou %s.",
		MONSTER_404: "Esse lugar está reservado para um monstro feroz.",
		ZONE_TOWER: "A torre do Mago",
		ZONE_MUSEUM: "Museu",
		ZONE_TOWN: "Vilarejo de Amberfall",
		ZONE_ARENA: "Arena",
		ZONE_CEMETERY_1: "Cemitério 1",
		ZONE_CEMETERY_2: "Cemitério 2",
		ZONE_CEMETERY_3: "Cemitério 3",
		ZONE_SEWER_1: "Esgoto 1",
		ZONE_SEWER_2: "Esgoto 2",
		ZONE_SEWER_3: "Esgoto 3",
		ZONE_CRYPT_1: "Esgoto 1",
		ZONE_CRYPT_2: "Esgoto 2",
		ZONE_CRYPT_3: "Esgoto 3",
		ZONE_FOREST: "Floresta",
		ZONE_DEN: "Covil dos Ladrões",
		ZONE_DEBUG: "Debug",
		MSG_TUT_MOVE: "Mova-se com WASD",
		MSG_TUT_MOVE_A: "Mova-se com o analógido esquerdo ou com o D-Pad",
		MSG_TUT_ATTACK: "Aperte e segure as setinhas para atacar",
		MSG_TUT_ATTACK_A: "Use o analógico direito para atacar",
		MSG_TUT_INTERACT: "Pressione a tecla de espaço para atacar",
		MSG_TUT_INTERACT_A: "Pressione A para interagir",
		MSG_TUT_GAMEPAD: "(ou use o controle)",
		MSG_TUT_DASH: "Pressione shift para dar um dash",
		MSG_TUT_DASH_A: "Pressione B para dar um dash",
		MSG_TUT_TOTEM: "Pressione X para posicionar um totem",
		MSG_TUT_TOTEM_A: "Pressione X para posicionar um totem",
		MSG_TUT_SOUL: "Pressione Z para usar o Soul Blast",
		MSG_TUT_SOUL_A: "Pressione Y para usar o Soul Blast",
		ACH_TITLE_ALIVE: "Still Alive",
		ACH_DESC_ALIVE: "Começando do Cemitério, saia da Cripta sem morrer.",
		ACH_TITLE_DEAD: "Jogando Morto",
		ACH_DESC_DEAD: "Começando do Cemitério, saia da Cripta sem ressuscitar.",
		ACH_TITLE_EMPTY: "Mãos Vazias",
		ACH_DESC_EMPTY: "Sem comprar nenhum item previamente, vá do Cemitério à Cripta.",
		ACH_TITLE_SPEED: "Speed Run",
		ACH_DESC_SPEED: "Começando do Cemitério, saia da Cripta em 20 minutos ou menos.",
		ACH_TITLE_MERCHANTS: "Assassino de Vendedores",
		ACH_DESC_MERCHANTS: "Mate 12 mercadores em uma jogatina.",
		ACH_TITLE_RESCUE: "Bom Samaritano",
		ACH_DESC_RESCUE: "Resgate 3 reféns em uma jogatina.",
		ACH_TITLE_SOULS: "Colecionador de Almas",
		ACH_DESC_SOULS: "Colete 30 Soul Orbs em uma jogatina.",
		WORN_ON_THE_X: "Equipado para %s",
		MYSTERY_ITEM: "Não se sabe muito sobre esse misterioso item",
		DAMAGE_TAKEN_FROM_X: "Dano recebido de %s",
		DAMAGE_TYPE_FIRE: "Fogo",
		DAMAGE_TYPE_ICE: "Gelo",
		SLOT_HEAD: "Cabeça",
		SLOT_CHEST: "Peito",
		SLOT_HANDS: "Mãos",
		SLOT_FEET: "Pés",
		SLOT_FINGER: "Dedos",
		SLOT_WEAPON: "Bainha",
		SLOT_TOTEM: "Coldre de Totems",
		SLOT_LIGHT: "Gancho Leve",
		SLOT_BOOK: "Bolsa de Livros",
		STAT_HEALTH: "Vida: %s / %s",
		STAT_SPEED: "Velocidade",
		STAT_ATTACK: "Ataque",
		STAT_MAGIC: "Soul Power",
		STAT_ARMOR: "Armadura",
		STAT_PROJECTILECOUNT: "Número de Projéteis",
		STAT_PROJECTILEVARIANCE: "Discrepância de Projéteis",
		STAT_PROJECTILESPREAD: "Propagação de Projéteis",
		STAT_ATTACKCOOLDOWN: "Cooldown do Ataque",
		STAT_TOTEMDURATION: "Duração do Totem",
		STAT_TOTEMEFFECT: "Efeito do Totem",
		STAT_TOTEMCOOLDOWN: "Tempo de recarga do Totem",
		STAT_TOTEMRADIUS: "Raio de alcance do Totem",
		STAT_ALIGNMENT: "Alinhamento",
		random: "Aleatório",
		raga: "Raga",
		moto: "Moto",
		luna: "Luna",
		wizard: "Wizard",
		engineer: "Engenheiro"
	}
});
